# configs/env/pursuit_v4.yaml

# Pursuit-v4 基础环境配置
environment:
  name: "pursuit_v4"
  n_agents: 8                     # 智能体数量
  max_cycles: 1000                 # 最大回合步数
  render_mode: "rgb_array"         # 渲染模式 (none, human, rgb_array)
  
  # 观测空间配置
  observation:
    type: "feature_extracted"      # 特征提取方式 (raw, feature_extracted)
    feature_dim: 30                # 特征维度
    include:                       # 包含的特征类型
      - "agent_position"           # 智能体位置
      - "prey_position"            # 猎物位置
      - "obstacle_distance"        # 障碍物距离
      - "agent_velocity"           # 智能体速度
      - "goal_direction"           # 目标方向向量
  
  # 奖励配置
  reward:
    capture_reward: 10.0           # 捕获猎物的奖励
    collision_penalty: -1.0        # 碰撞惩罚
    time_penalty: -0.01            # 时间惩罚
    communication_cost: -0.05      # 通信代价
    
  # 高级设置
  advanced:
    use_partial_obs: true          # 使用部分可观测环境
    obs_radius: 5                  # 观测半径
    enable_dynamic_obstacles: false # 启用动态障碍物
    
  # 硬件优化
  hardware:
    num_cpu_cores: 6               # 环境仿真使用的CPU核心数
    gpu_acceleration: false        # 是否使用GPU加速环境